// apps/temp-ui-vue/src/pages/login.vue
<script setup lang="ts">
import { LoginForm } from '@/features/authentication';
import { authCheckStatus } from '@/features/authentication/services';

const { query } = useRoute();
const router = useRouter();

onMounted(async () => {
	try {
		await authCheckStatus();
		router.push(query.redirect_to?.toString() || '/');
	} catch (error) {
		console.error('Error checking auth status:', error);
	}
});
</script>

<template>
	<div class="flex min-h-screen items-center justify-center bg-gradient-to-br from-blue-100 via-pink-100 to-blue-200">
		<LoginForm :redirect_to="query.redirect_to?.toString()" />
	</div>
</template>

<route lang="yaml">
meta:
  layout: Blank
</route>

// apps/temp-ui-react/src/routes/auth/_layout/login.tsx
import { createFileRoute } from '@tanstack/react-router'
import { LoginForm } from '@/features/authentication'

export const Route = createFileRoute('/auth/_layout/login')({
  component: Login,
})

function Login() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8">
        <LoginForm />
      </div>
    </div>
  )
}
